spring:
    cloud:
        consul:
            config:
                enabled: true
            host: localhost
            port: 8500
server:
    port: 8081
message:
    greeting: Welcome Home Mi Dear
message:
    welcome: Welcome To GitHub
